### ISSUE TITLE
[Bug]: can't display the data and time of the conversation

### ISSUE THREAD

**Issue by newtec-foggia** [Ercogx/filament-openai-assistant#3]
### What happened?

I modified the blade file to display the user and assistant name but I can't display the data and time of the conversation, can you help me?

### How to reproduce the bug

[blade_file.pdf](https://github.com/user-attachments/files/17533617/blade_file.pdf)

### Package Version

1.0.3

### PHP Version

8.2.0

### Laravel Version

10.48.17

### Which operating systems does with happen with?

Windows

**Comment by Ercogx** [comment]
@newtec-foggia Hey, you can upgrade to 1.0.4. I added unix label `createdAt` to the `$message` variable
